name: .NET Run tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
env:
  CONFIGURATION: Release
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # Restore nugets
    - name: Restore
      run: dotnet restore

    # Build solution
    - name: Build
      run: dotnet build --no-restore

    # Execute TEST
    - name: Test
      run: dotnet test --no-build --verbosity normal